name: Just Compile
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'The Pack Version'
        required: false
        default: '1.0.0'
        type: string

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


jobs:
  AtmoPack-Vanilla_Release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pack
        uses: actions/checkout@v3
      - name: node index
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACK_VERSION: ${{ inputs.version }}
        run: |
          npm ci
          node index
      - name: AtmoPackMaker
        uses: actions/upload-artifact@v3
        with:
          name: ${{ vars.PACK_NAME }}
          path: ${{ vars.PACK_NAME }}.zip
